name = "Python"
uuid = "bf110322-bcf6-11e8-1190-4d0503f9cc24"
authors = ["Yang Li <liyangsdu@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
